name: PHPUnit Tests

on:
  push:
#    branches:
#      - trunk
#      - '3.[7-9]'
#      - '[4-9].[0-9]'
#    tags:
#      - '[0-9]+.[0-9]'
#      - '[0-9]+.[0-9].[0-9]+'
  pull_request:
    branches:
      - trunk
      - '3.[7-9]'
      - '[4-9].[0-9]'
  workflow_dispatch:
  # Once weekly On Sundays at 00:00 UTC.
  schedule:
    - cron: '0 0 * * 0'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

env:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: ${{ true }}
  LOCAL_PHP_MEMCACHED: ${{ false }}
  SLOW_TESTS: 'external-http,media,restapi'

jobs:
  # Runs the PHPUnit tests for WordPress.
  #
  # Note: Steps running tests on PHP 8.1 + 8.2 are allowed to "continue-on-error" (for now).
  # This prevents workflow runs from being marked as "failed" when only PHP 8.1/8.2 fails.
  #
  # Performs the following steps:
  # - Sets environment variables.
  # - Sets up the environment variables needed for testing with memcached (if desired).
  # - Installs NodeJS.
  # - Installs NPM dependencies
  # - Configures caching for Composer.
  # - Installs Composer dependencies.
  # - Logs Docker debug information (about the Docker installation within the runner).
  # - Starts the WordPress Docker container.
  # - Logs general debug information about the runner.
  # - Logs the running Docker containers.
  # - Logs debug information from inside the WordPress Docker container.
  # - Logs debug information about what's installed within the WordPress Docker containers.
  # - Install WordPress within the Docker container.
  # - Run the PHPUnit tests.
  # - Ensures version-controlled files are not modified or deleted.
  # - Checks out the WordPress Test reporter repository.
  # - Reconnect the directory to the Git repository.
  # - Submit the test results to the WordPress.org host test results.
  test-php:
    name: ${{ matrix.php }}${{ matrix.multisite && ' multisite' || '' }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
#    if: ${{ github.repository == 'WordPress/wordpress-develop' || github.event_name == 'pull_request' }}
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2' ]
        os: [ ubuntu-latest ]
        multisite: [ false, true ]

        include:
          - php: '7.4'
            os: ubuntu-latest
            multisite: false
          - php: '5.6'
            os: ubuntu-latest
            multisite: true

    env:
      PHPUNIT_CONFIG: ${{ matrix.multisite && 'tests/phpunit/multisite.xml' || 'phpunit.xml.dist' }}

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=-1, display_errors=On, log_errors_max_len=0
          coverage: none
          tools: phpunit-polyfills

      - name: Ensure correct PHPUnit version is available
        if: ${{ matrix.php == '8.2' }}
        run: composer global update yoast/phpunit-polyfills --with-all-dependencies --ignore-platform-reqs

      - run: cp wp-tests-config-sample.php wp-tests-config.php
      - run: sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
      - run: sed -i "s/yourusernamehere/root/" wp-tests-config.php
      - run: sed -i "s/yourpasswordhere//" wp-tests-config.php
      - run: sed -i "s/localhost/127.0.0.1:3306/" wp-tests-config.php

      - name: Show PHPUnit version
        run: phpunit --version

      - name: Run PHPUnit tests - single site
        continue-on-error: ${{ matrix.php == '8.1' || matrix.php == '8.2' }}
        if: ${{ matrix.multisite == false }}
        run: phpunit

      - name: Run PHPUnit tests - multi site
        continue-on-error: ${{ matrix.php == '8.1' || matrix.php == '8.2' }}
        if: ${{ matrix.multisite == true }}
        run: phpunit -c tests/phpunit/multisite.xml

      - name: Run AJAX tests - single site
        continue-on-error: ${{ matrix.php == '8.1' || matrix.php == '8.2' }}
        if: ${{ matrix.multisite == false }}
        run: phpunit --group ajax

      - name: Run AJAX tests - multi site
        continue-on-error: ${{ matrix.php == '8.2' }}
        if: ${{ matrix.multisite == true }}
        run: phpunit -c tests/phpunit/multisite.xml --group ajax

      - name: Run ms-files tests as a multisite install
        continue-on-error: ${{ matrix.php == '8.2' }}
        if: ${{ matrix.multisite }}
        run: phpunit -c tests/phpunit/multisite.xml --group ms-files

      - name: Run external HTTP tests
        continue-on-error: ${{ matrix.php == '8.2' }}
        if: ${{ ! matrix.multisite }}
        run: phpunit --group external-http
